# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QFrame,
    QHBoxLayout, QLabel, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QSpacerItem,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_qMain(object):
    def setupUi(self, qMain):
        if not qMain.objectName():
            qMain.setObjectName(u"qMain")
        qMain.resize(1224, 819)
        self.qBody = QWidget(qMain)
        self.qBody.setObjectName(u"qBody")
        self.verticalLayout_12 = QVBoxLayout(self.qBody)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.frmSystem = QFrame(self.qBody)
        self.frmSystem.setObjectName(u"frmSystem")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmSystem.sizePolicy().hasHeightForWidth())
        self.frmSystem.setSizePolicy(sizePolicy)
        self.horizontalLayout_4 = QHBoxLayout(self.frmSystem)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.frmSystemEEPROM = QFrame(self.frmSystem)
        self.frmSystemEEPROM.setObjectName(u"frmSystemEEPROM")
        self.frmSystemEEPROM.setEnabled(False)
        self.verticalLayout_4 = QVBoxLayout(self.frmSystemEEPROM)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.btnEEPROMWipe_A = QPushButton(self.frmSystemEEPROM)
        self.btnEEPROMWipe_A.setObjectName(u"btnEEPROMWipe_A")

        self.verticalLayout_4.addWidget(self.btnEEPROMWipe_A)

        self.btnEEPROMLoad_A = QPushButton(self.frmSystemEEPROM)
        self.btnEEPROMLoad_A.setObjectName(u"btnEEPROMLoad_A")

        self.verticalLayout_4.addWidget(self.btnEEPROMLoad_A)

        self.btnEEPROMSave_A = QPushButton(self.frmSystemEEPROM)
        self.btnEEPROMSave_A.setObjectName(u"btnEEPROMSave_A")

        self.verticalLayout_4.addWidget(self.btnEEPROMSave_A)


        self.horizontalLayout_4.addWidget(self.frmSystemEEPROM)

        self.frmSystemControls = QFrame(self.frmSystem)
        self.frmSystemControls.setObjectName(u"frmSystemControls")
        sizePolicy.setHeightForWidth(self.frmSystemControls.sizePolicy().hasHeightForWidth())
        self.frmSystemControls.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.frmSystemControls)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, -1, 10)
        self.frmSystemCOMList = QFrame(self.frmSystemControls)
        self.frmSystemCOMList.setObjectName(u"frmSystemCOMList")
        self.horizontalLayout = QHBoxLayout(self.frmSystemCOMList)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.btnSerialConnect = QPushButton(self.frmSystemCOMList)
        self.btnSerialConnect.setObjectName(u"btnSerialConnect")

        self.horizontalLayout.addWidget(self.btnSerialConnect)

        self.btnSerialDisconnect = QPushButton(self.frmSystemCOMList)
        self.btnSerialDisconnect.setObjectName(u"btnSerialDisconnect")
        self.btnSerialDisconnect.setEnabled(False)

        self.horizontalLayout.addWidget(self.btnSerialDisconnect)

        self.btnSerialRefresh = QPushButton(self.frmSystemCOMList)
        self.btnSerialRefresh.setObjectName(u"btnSerialRefresh")

        self.horizontalLayout.addWidget(self.btnSerialRefresh)

        self.boxComportList = QComboBox(self.frmSystemCOMList)
        self.boxComportList.setObjectName(u"boxComportList")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.boxComportList.sizePolicy().hasHeightForWidth())
        self.boxComportList.setSizePolicy(sizePolicy1)

        self.horizontalLayout.addWidget(self.boxComportList)


        self.verticalLayout.addWidget(self.frmSystemCOMList)

        self.frame = QFrame(self.frmSystemControls)
        self.frame.setObjectName(u"frame")
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.labelConnected = QLabel(self.frame)
        self.labelConnected.setObjectName(u"labelConnected")
        sizePolicy.setHeightForWidth(self.labelConnected.sizePolicy().hasHeightForWidth())
        self.labelConnected.setSizePolicy(sizePolicy)
        self.labelConnected.setMinimumSize(QSize(250, 0))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.labelConnected.setFont(font)
        self.labelConnected.setFrameShape(QFrame.Shape.Panel)
        self.labelConnected.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelConnected.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_2.addWidget(self.labelConnected)

        self.spacerConnected2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.spacerConnected2)


        self.verticalLayout.addWidget(self.frame)


        self.horizontalLayout_4.addWidget(self.frmSystemControls)


        self.verticalLayout_12.addWidget(self.frmSystem)

        self.frmAxisControls = QFrame(self.qBody)
        self.frmAxisControls.setObjectName(u"frmAxisControls")
        self.frmAxisControls.setEnabled(False)
        sizePolicy.setHeightForWidth(self.frmAxisControls.sizePolicy().hasHeightForWidth())
        self.frmAxisControls.setSizePolicy(sizePolicy)
        self.frmAxisControls.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.frmAxisControls)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.frmAxisEnable_A = QFrame(self.frmAxisControls)
        self.frmAxisEnable_A.setObjectName(u"frmAxisEnable_A")
        self.frmAxisEnable_A.setFrameShape(QFrame.Shape.NoFrame)
        self.frmAxisEnable_A.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.frmAxisEnable_A)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.btnEnable_A = QPushButton(self.frmAxisEnable_A)
        self.btnEnable_A.setObjectName(u"btnEnable_A")

        self.verticalLayout_9.addWidget(self.btnEnable_A)

        self.frmAxis_A = QFrame(self.frmAxisEnable_A)
        self.frmAxis_A.setObjectName(u"frmAxis_A")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.frmAxis_A.sizePolicy().hasHeightForWidth())
        self.frmAxis_A.setSizePolicy(sizePolicy2)
        self.frmAxis_A.setMinimumSize(QSize(0, 0))
        self.frmAxis_A.setMaximumSize(QSize(16777215, 250))
        self.frmAxis_A.setFrameShape(QFrame.Shape.NoFrame)
        self.frmAxis_A.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.frmAxis_A)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.frmAxisSliders_A = QFrame(self.frmAxis_A)
        self.frmAxisSliders_A.setObjectName(u"frmAxisSliders_A")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frmAxisSliders_A.sizePolicy().hasHeightForWidth())
        self.frmAxisSliders_A.setSizePolicy(sizePolicy3)
        self.frmAxisSliders_A.setMinimumSize(QSize(165, 220))
        self.frmAxisSliders_A.setFrameShape(QFrame.Shape.NoFrame)
        self.frmAxisSliders_A.setFrameShadow(QFrame.Shadow.Raised)
        self.labelTarget_A = QLabel(self.frmAxisSliders_A)
        self.labelTarget_A.setObjectName(u"labelTarget_A")
        self.labelTarget_A.setGeometry(QRect(100, 160, 60, 25))
        self.labelTarget_A.setFrameShape(QFrame.Shape.Panel)
        self.labelTarget_A.setFrameShadow(QFrame.Shadow.Raised)
        self.labelTarget_A.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderTarget_A = QSlider(self.frmAxisSliders_A)
        self.sliderTarget_A.setObjectName(u"sliderTarget_A")
        self.sliderTarget_A.setGeometry(QRect(120, 10, 20, 150))
        self.sliderTarget_A.setOrientation(Qt.Orientation.Vertical)
        self.labelTargetReported_A = QLabel(self.frmAxisSliders_A)
        self.labelTargetReported_A.setObjectName(u"labelTargetReported_A")
        self.labelTargetReported_A.setGeometry(QRect(100, 190, 60, 25))
        self.labelTargetReported_A.setFrameShape(QFrame.Shape.Panel)
        self.labelTargetReported_A.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelTargetReported_A.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelABZ_A = QLabel(self.frmAxisSliders_A)
        self.labelABZ_A.setObjectName(u"labelABZ_A")
        self.labelABZ_A.setGeometry(QRect(50, 190, 40, 25))
        self.labelABZ_A.setFrameShape(QFrame.Shape.Panel)
        self.labelABZ_A.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelABZ_A.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelSPI_A = QLabel(self.frmAxisSliders_A)
        self.labelSPI_A.setObjectName(u"labelSPI_A")
        self.labelSPI_A.setGeometry(QRect(0, 190, 40, 25))
        self.labelSPI_A.setFrameShape(QFrame.Shape.Panel)
        self.labelSPI_A.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelSPI_A.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderABZ_A = QSlider(self.frmAxisSliders_A)
        self.sliderABZ_A.setObjectName(u"sliderABZ_A")
        self.sliderABZ_A.setGeometry(QRect(60, 10, 20, 150))
        self.sliderABZ_A.setOrientation(Qt.Orientation.Vertical)
        self.sliderSPI_A = QSlider(self.frmAxisSliders_A)
        self.sliderSPI_A.setObjectName(u"sliderSPI_A")
        self.sliderSPI_A.setGeometry(QRect(10, 10, 20, 150))
        self.sliderSPI_A.setOrientation(Qt.Orientation.Vertical)
        self.label = QLabel(self.frmAxisSliders_A)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 160, 40, 25))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.frmAxisSliders_A)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 160, 40, 25))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderTarget_A.raise_()
        self.labelTarget_A.raise_()
        self.labelTargetReported_A.raise_()
        self.labelABZ_A.raise_()
        self.labelSPI_A.raise_()
        self.sliderABZ_A.raise_()
        self.sliderSPI_A.raise_()
        self.label.raise_()
        self.label_2.raise_()

        self.horizontalLayout_7.addWidget(self.frmAxisSliders_A)

        self.frmControls_A = QFrame(self.frmAxis_A)
        self.frmControls_A.setObjectName(u"frmControls_A")
        sizePolicy2.setHeightForWidth(self.frmControls_A.sizePolicy().hasHeightForWidth())
        self.frmControls_A.setSizePolicy(sizePolicy2)
        self.frmControls_A.setMaximumSize(QSize(250, 16777215))
        self.frmControls_A.setFrameShape(QFrame.Shape.NoFrame)
        self.frmControls_A.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frmControls_A)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.frmCenter_A = QFrame(self.frmControls_A)
        self.frmCenter_A.setObjectName(u"frmCenter_A")
        sizePolicy3.setHeightForWidth(self.frmCenter_A.sizePolicy().hasHeightForWidth())
        self.frmCenter_A.setSizePolicy(sizePolicy3)
        self.frmCenter_A.setFrameShape(QFrame.Shape.NoFrame)
        self.frmCenter_A.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frmCenter_A)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.crmCenterButtons_A = QFrame(self.frmCenter_A)
        self.crmCenterButtons_A.setObjectName(u"crmCenterButtons_A")
        self.crmCenterButtons_A.setFrameShape(QFrame.Shape.NoFrame)
        self.crmCenterButtons_A.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.crmCenterButtons_A)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.btnNudgeUp_A = QPushButton(self.crmCenterButtons_A)
        self.btnNudgeUp_A.setObjectName(u"btnNudgeUp_A")

        self.verticalLayout_2.addWidget(self.btnNudgeUp_A)

        self.btnNudgeDown_A = QPushButton(self.crmCenterButtons_A)
        self.btnNudgeDown_A.setObjectName(u"btnNudgeDown_A")

        self.verticalLayout_2.addWidget(self.btnNudgeDown_A)


        self.horizontalLayout_3.addWidget(self.crmCenterButtons_A)

        self.lblNudgeCenter_A = QLabel(self.frmCenter_A)
        self.lblNudgeCenter_A.setObjectName(u"lblNudgeCenter_A")
        sizePolicy2.setHeightForWidth(self.lblNudgeCenter_A.sizePolicy().hasHeightForWidth())
        self.lblNudgeCenter_A.setSizePolicy(sizePolicy2)
        self.lblNudgeCenter_A.setFrameShape(QFrame.Shape.NoFrame)
        self.lblNudgeCenter_A.setFrameShadow(QFrame.Shadow.Plain)
        self.lblNudgeCenter_A.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lblNudgeCenter_A.setWordWrap(True)

        self.horizontalLayout_3.addWidget(self.lblNudgeCenter_A)


        self.verticalLayout_3.addWidget(self.frmCenter_A)

        self.labelEnabled_A = QLabel(self.frmControls_A)
        self.labelEnabled_A.setObjectName(u"labelEnabled_A")
        self.labelEnabled_A.setFrameShape(QFrame.Shape.NoFrame)
        self.labelEnabled_A.setFrameShadow(QFrame.Shadow.Plain)
        self.labelEnabled_A.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.labelEnabled_A)

        self.frmPID_A = QFrame(self.frmControls_A)
        self.frmPID_A.setObjectName(u"frmPID_A")
        self.frmPID_A.setFrameShape(QFrame.Shape.NoFrame)
        self.frmPID_A.setFrameShadow(QFrame.Shadow.Raised)
        self.formLayout = QFormLayout(self.frmPID_A)
        self.formLayout.setObjectName(u"formLayout")
        self.lblPIDAP_A = QLabel(self.frmPID_A)
        self.lblPIDAP_A.setObjectName(u"lblPIDAP_A")
        self.lblPIDAP_A.setMinimumSize(QSize(60, 16))
        self.lblPIDAP_A.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAP_A.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAP_A.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.lblPIDAP_A)

        self.lblPIDAI_A = QLabel(self.frmPID_A)
        self.lblPIDAI_A.setObjectName(u"lblPIDAI_A")
        self.lblPIDAI_A.setMinimumSize(QSize(60, 16))
        self.lblPIDAI_A.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAI_A.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAI_A.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout.setWidget(3, QFormLayout.ItemRole.FieldRole, self.lblPIDAI_A)

        self.lblPIDAD_A = QLabel(self.frmPID_A)
        self.lblPIDAD_A.setObjectName(u"lblPIDAD_A")
        self.lblPIDAD_A.setMinimumSize(QSize(60, 16))
        self.lblPIDAD_A.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAD_A.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAD_A.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout.setWidget(5, QFormLayout.ItemRole.FieldRole, self.lblPIDAD_A)

        self.frmKp_A = QFrame(self.frmPID_A)
        self.frmKp_A.setObjectName(u"frmKp_A")
        self.frmKp_A.setMinimumSize(QSize(60, 16))
        self.frmKp_A.setFrameShape(QFrame.Shape.Panel)
        self.frmKp_A.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKp_A = QPushButton(self.frmKp_A)
        self.btnKp_A.setObjectName(u"btnKp_A")
        self.btnKp_A.setGeometry(QRect(0, -1, 60, 20))
        self.btnKp_A.setMinimumSize(QSize(60, 16))
        self.btnKp_A.setText(u"0.000")
        self.btnKp_A.setFlat(True)

        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.frmKp_A)

        self.frmKi_A = QFrame(self.frmPID_A)
        self.frmKi_A.setObjectName(u"frmKi_A")
        self.frmKi_A.setMinimumSize(QSize(60, 16))
        self.frmKi_A.setFrameShape(QFrame.Shape.Panel)
        self.frmKi_A.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKi_A = QPushButton(self.frmKi_A)
        self.btnKi_A.setObjectName(u"btnKi_A")
        self.btnKi_A.setGeometry(QRect(0, -1, 60, 20))
        self.btnKi_A.setMinimumSize(QSize(60, 16))
        self.btnKi_A.setText(u"0.000")
        self.btnKi_A.setFlat(True)

        self.formLayout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.frmKi_A)

        self.frmKd_A = QFrame(self.frmPID_A)
        self.frmKd_A.setObjectName(u"frmKd_A")
        self.frmKd_A.setMinimumSize(QSize(60, 16))
        self.frmKd_A.setFrameShape(QFrame.Shape.Panel)
        self.frmKd_A.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKd_A = QPushButton(self.frmKd_A)
        self.btnKd_A.setObjectName(u"btnKd_A")
        self.btnKd_A.setGeometry(QRect(0, -1, 60, 20))
        self.btnKd_A.setMinimumSize(QSize(60, 16))
        self.btnKd_A.setText(u"0.000")
        self.btnKd_A.setFlat(True)

        self.formLayout.setWidget(5, QFormLayout.ItemRole.LabelRole, self.frmKd_A)


        self.verticalLayout_3.addWidget(self.frmPID_A)


        self.horizontalLayout_7.addWidget(self.frmControls_A)


        self.verticalLayout_9.addWidget(self.frmAxis_A)


        self.horizontalLayout_10.addWidget(self.frmAxisEnable_A)

        self.frmAxisEnable_B = QFrame(self.frmAxisControls)
        self.frmAxisEnable_B.setObjectName(u"frmAxisEnable_B")
        self.frmAxisEnable_B.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_10 = QVBoxLayout(self.frmAxisEnable_B)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.btnEnable_B = QPushButton(self.frmAxisEnable_B)
        self.btnEnable_B.setObjectName(u"btnEnable_B")

        self.verticalLayout_10.addWidget(self.btnEnable_B)

        self.frmAxis_B = QFrame(self.frmAxisEnable_B)
        self.frmAxis_B.setObjectName(u"frmAxis_B")
        sizePolicy2.setHeightForWidth(self.frmAxis_B.sizePolicy().hasHeightForWidth())
        self.frmAxis_B.setSizePolicy(sizePolicy2)
        self.frmAxis_B.setMinimumSize(QSize(0, 0))
        self.frmAxis_B.setMaximumSize(QSize(16777215, 250))
        self.frmAxis_B.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.frmAxis_B)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.frmAxisSliders_B = QFrame(self.frmAxis_B)
        self.frmAxisSliders_B.setObjectName(u"frmAxisSliders_B")
        sizePolicy3.setHeightForWidth(self.frmAxisSliders_B.sizePolicy().hasHeightForWidth())
        self.frmAxisSliders_B.setSizePolicy(sizePolicy3)
        self.frmAxisSliders_B.setMinimumSize(QSize(165, 220))
        self.frmAxisSliders_B.setFrameShadow(QFrame.Shadow.Raised)
        self.labelTarget_B = QLabel(self.frmAxisSliders_B)
        self.labelTarget_B.setObjectName(u"labelTarget_B")
        self.labelTarget_B.setGeometry(QRect(100, 160, 60, 25))
        self.labelTarget_B.setFrameShape(QFrame.Shape.Panel)
        self.labelTarget_B.setFrameShadow(QFrame.Shadow.Raised)
        self.labelTarget_B.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderTarget_B = QSlider(self.frmAxisSliders_B)
        self.sliderTarget_B.setObjectName(u"sliderTarget_B")
        self.sliderTarget_B.setGeometry(QRect(120, 10, 20, 150))
        self.sliderTarget_B.setOrientation(Qt.Orientation.Vertical)
        self.labelTargetReported_B = QLabel(self.frmAxisSliders_B)
        self.labelTargetReported_B.setObjectName(u"labelTargetReported_B")
        self.labelTargetReported_B.setGeometry(QRect(100, 190, 60, 25))
        self.labelTargetReported_B.setFrameShape(QFrame.Shape.Panel)
        self.labelTargetReported_B.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelTargetReported_B.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderSPI_B = QSlider(self.frmAxisSliders_B)
        self.sliderSPI_B.setObjectName(u"sliderSPI_B")
        self.sliderSPI_B.setGeometry(QRect(10, 10, 20, 150))
        self.sliderSPI_B.setOrientation(Qt.Orientation.Vertical)
        self.labelSPI_B = QLabel(self.frmAxisSliders_B)
        self.labelSPI_B.setObjectName(u"labelSPI_B")
        self.labelSPI_B.setGeometry(QRect(0, 190, 40, 25))
        self.labelSPI_B.setFrameShape(QFrame.Shape.Panel)
        self.labelSPI_B.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelSPI_B.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderABZ_B = QSlider(self.frmAxisSliders_B)
        self.sliderABZ_B.setObjectName(u"sliderABZ_B")
        self.sliderABZ_B.setGeometry(QRect(60, 10, 20, 150))
        self.sliderABZ_B.setOrientation(Qt.Orientation.Vertical)
        self.labelABZ_B = QLabel(self.frmAxisSliders_B)
        self.labelABZ_B.setObjectName(u"labelABZ_B")
        self.labelABZ_B.setGeometry(QRect(50, 190, 40, 25))
        self.labelABZ_B.setFrameShape(QFrame.Shape.Panel)
        self.labelABZ_B.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelABZ_B.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.frmAxisSliders_B)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 160, 40, 25))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.frmAxisSliders_B)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 160, 40, 25))
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderTarget_B.raise_()
        self.labelTarget_B.raise_()
        self.labelTargetReported_B.raise_()
        self.sliderSPI_B.raise_()
        self.labelSPI_B.raise_()
        self.sliderABZ_B.raise_()
        self.labelABZ_B.raise_()
        self.label_4.raise_()
        self.label_3.raise_()

        self.horizontalLayout_8.addWidget(self.frmAxisSliders_B)

        self.frmControls_B = QFrame(self.frmAxis_B)
        self.frmControls_B.setObjectName(u"frmControls_B")
        sizePolicy2.setHeightForWidth(self.frmControls_B.sizePolicy().hasHeightForWidth())
        self.frmControls_B.setSizePolicy(sizePolicy2)
        self.frmControls_B.setMaximumSize(QSize(250, 16777215))
        self.frmControls_B.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frmControls_B)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.frmCenter_B = QFrame(self.frmControls_B)
        self.frmCenter_B.setObjectName(u"frmCenter_B")
        sizePolicy3.setHeightForWidth(self.frmCenter_B.sizePolicy().hasHeightForWidth())
        self.frmCenter_B.setSizePolicy(sizePolicy3)
        self.frmCenter_B.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frmCenter_B)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.crmCenterButtons_B = QFrame(self.frmCenter_B)
        self.crmCenterButtons_B.setObjectName(u"crmCenterButtons_B")
        self.crmCenterButtons_B.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.crmCenterButtons_B)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.btnNudgeUp_B = QPushButton(self.crmCenterButtons_B)
        self.btnNudgeUp_B.setObjectName(u"btnNudgeUp_B")

        self.verticalLayout_6.addWidget(self.btnNudgeUp_B)

        self.btnNudgeDown_B = QPushButton(self.crmCenterButtons_B)
        self.btnNudgeDown_B.setObjectName(u"btnNudgeDown_B")

        self.verticalLayout_6.addWidget(self.btnNudgeDown_B)


        self.horizontalLayout_5.addWidget(self.crmCenterButtons_B)

        self.lblNudgeCenter_B = QLabel(self.frmCenter_B)
        self.lblNudgeCenter_B.setObjectName(u"lblNudgeCenter_B")
        sizePolicy2.setHeightForWidth(self.lblNudgeCenter_B.sizePolicy().hasHeightForWidth())
        self.lblNudgeCenter_B.setSizePolicy(sizePolicy2)
        self.lblNudgeCenter_B.setFrameShape(QFrame.Shape.NoFrame)
        self.lblNudgeCenter_B.setFrameShadow(QFrame.Shadow.Plain)
        self.lblNudgeCenter_B.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lblNudgeCenter_B.setWordWrap(True)

        self.horizontalLayout_5.addWidget(self.lblNudgeCenter_B)


        self.verticalLayout_5.addWidget(self.frmCenter_B)

        self.labelEnabled_B = QLabel(self.frmControls_B)
        self.labelEnabled_B.setObjectName(u"labelEnabled_B")
        self.labelEnabled_B.setFrameShape(QFrame.Shape.NoFrame)
        self.labelEnabled_B.setFrameShadow(QFrame.Shadow.Plain)
        self.labelEnabled_B.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_5.addWidget(self.labelEnabled_B)

        self.frmPID_B = QFrame(self.frmControls_B)
        self.frmPID_B.setObjectName(u"frmPID_B")
        self.frmPID_B.setFrameShadow(QFrame.Shadow.Raised)
        self.formLayout_2 = QFormLayout(self.frmPID_B)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.lblPIDAP_B = QLabel(self.frmPID_B)
        self.lblPIDAP_B.setObjectName(u"lblPIDAP_B")
        self.lblPIDAP_B.setMinimumSize(QSize(60, 16))
        self.lblPIDAP_B.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAP_B.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAP_B.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(1, QFormLayout.ItemRole.FieldRole, self.lblPIDAP_B)

        self.lblPIDAI_B = QLabel(self.frmPID_B)
        self.lblPIDAI_B.setObjectName(u"lblPIDAI_B")
        self.lblPIDAI_B.setMinimumSize(QSize(60, 16))
        self.lblPIDAI_B.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAI_B.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAI_B.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(3, QFormLayout.ItemRole.FieldRole, self.lblPIDAI_B)

        self.lblPIDAD_B = QLabel(self.frmPID_B)
        self.lblPIDAD_B.setObjectName(u"lblPIDAD_B")
        self.lblPIDAD_B.setMinimumSize(QSize(60, 16))
        self.lblPIDAD_B.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAD_B.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAD_B.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(5, QFormLayout.ItemRole.FieldRole, self.lblPIDAD_B)

        self.frmKp_B = QFrame(self.frmPID_B)
        self.frmKp_B.setObjectName(u"frmKp_B")
        self.frmKp_B.setMinimumSize(QSize(60, 16))
        self.frmKp_B.setFrameShape(QFrame.Shape.Panel)
        self.frmKp_B.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKp_B = QPushButton(self.frmKp_B)
        self.btnKp_B.setObjectName(u"btnKp_B")
        self.btnKp_B.setGeometry(QRect(0, -1, 60, 20))
        self.btnKp_B.setMinimumSize(QSize(60, 16))
        self.btnKp_B.setText(u"0.000")
        self.btnKp_B.setFlat(True)

        self.formLayout_2.setWidget(1, QFormLayout.ItemRole.LabelRole, self.frmKp_B)

        self.frmKi_B = QFrame(self.frmPID_B)
        self.frmKi_B.setObjectName(u"frmKi_B")
        self.frmKi_B.setMinimumSize(QSize(60, 16))
        self.frmKi_B.setFrameShape(QFrame.Shape.Panel)
        self.frmKi_B.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKi_B = QPushButton(self.frmKi_B)
        self.btnKi_B.setObjectName(u"btnKi_B")
        self.btnKi_B.setGeometry(QRect(0, -1, 60, 20))
        self.btnKi_B.setMinimumSize(QSize(60, 16))
        self.btnKi_B.setText(u"0.000")
        self.btnKi_B.setFlat(True)

        self.formLayout_2.setWidget(3, QFormLayout.ItemRole.LabelRole, self.frmKi_B)

        self.frmKd_B = QFrame(self.frmPID_B)
        self.frmKd_B.setObjectName(u"frmKd_B")
        self.frmKd_B.setMinimumSize(QSize(60, 16))
        self.frmKd_B.setFrameShape(QFrame.Shape.Panel)
        self.frmKd_B.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKd_B = QPushButton(self.frmKd_B)
        self.btnKd_B.setObjectName(u"btnKd_B")
        self.btnKd_B.setGeometry(QRect(0, -1, 60, 20))
        self.btnKd_B.setMinimumSize(QSize(60, 16))
        self.btnKd_B.setText(u"0.000")
        self.btnKd_B.setFlat(True)

        self.formLayout_2.setWidget(5, QFormLayout.ItemRole.LabelRole, self.frmKd_B)


        self.verticalLayout_5.addWidget(self.frmPID_B)


        self.horizontalLayout_8.addWidget(self.frmControls_B)


        self.verticalLayout_10.addWidget(self.frmAxis_B)


        self.horizontalLayout_10.addWidget(self.frmAxisEnable_B)

        self.frmAxisEnable_C = QFrame(self.frmAxisControls)
        self.frmAxisEnable_C.setObjectName(u"frmAxisEnable_C")
        self.frmAxisEnable_C.setFrameShape(QFrame.Shape.NoFrame)
        self.frmAxisEnable_C.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.frmAxisEnable_C)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.btnEnable_C = QPushButton(self.frmAxisEnable_C)
        self.btnEnable_C.setObjectName(u"btnEnable_C")

        self.verticalLayout_11.addWidget(self.btnEnable_C)

        self.frmAxis_C = QFrame(self.frmAxisEnable_C)
        self.frmAxis_C.setObjectName(u"frmAxis_C")
        sizePolicy2.setHeightForWidth(self.frmAxis_C.sizePolicy().hasHeightForWidth())
        self.frmAxis_C.setSizePolicy(sizePolicy2)
        self.frmAxis_C.setMinimumSize(QSize(0, 0))
        self.frmAxis_C.setMaximumSize(QSize(16777215, 250))
        self.frmAxis_C.setFrameShape(QFrame.Shape.NoFrame)
        self.frmAxis_C.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.frmAxis_C)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.frmAxisSliders_C = QFrame(self.frmAxis_C)
        self.frmAxisSliders_C.setObjectName(u"frmAxisSliders_C")
        sizePolicy3.setHeightForWidth(self.frmAxisSliders_C.sizePolicy().hasHeightForWidth())
        self.frmAxisSliders_C.setSizePolicy(sizePolicy3)
        self.frmAxisSliders_C.setMinimumSize(QSize(165, 220))
        self.frmAxisSliders_C.setFrameShape(QFrame.Shape.NoFrame)
        self.frmAxisSliders_C.setFrameShadow(QFrame.Shadow.Raised)
        self.labelTarget_C = QLabel(self.frmAxisSliders_C)
        self.labelTarget_C.setObjectName(u"labelTarget_C")
        self.labelTarget_C.setGeometry(QRect(100, 160, 60, 25))
        self.labelTarget_C.setFrameShape(QFrame.Shape.Panel)
        self.labelTarget_C.setFrameShadow(QFrame.Shadow.Raised)
        self.labelTarget_C.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderTarget_C = QSlider(self.frmAxisSliders_C)
        self.sliderTarget_C.setObjectName(u"sliderTarget_C")
        self.sliderTarget_C.setGeometry(QRect(120, 10, 20, 150))
        self.sliderTarget_C.setOrientation(Qt.Orientation.Vertical)
        self.labelTargetReported_C = QLabel(self.frmAxisSliders_C)
        self.labelTargetReported_C.setObjectName(u"labelTargetReported_C")
        self.labelTargetReported_C.setGeometry(QRect(100, 190, 60, 25))
        self.labelTargetReported_C.setFrameShape(QFrame.Shape.Panel)
        self.labelTargetReported_C.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelTargetReported_C.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderSPI_C = QSlider(self.frmAxisSliders_C)
        self.sliderSPI_C.setObjectName(u"sliderSPI_C")
        self.sliderSPI_C.setGeometry(QRect(10, 10, 20, 150))
        self.sliderSPI_C.setOrientation(Qt.Orientation.Vertical)
        self.sliderABZ_C = QSlider(self.frmAxisSliders_C)
        self.sliderABZ_C.setObjectName(u"sliderABZ_C")
        self.sliderABZ_C.setGeometry(QRect(60, 10, 20, 150))
        self.sliderABZ_C.setOrientation(Qt.Orientation.Vertical)
        self.labelSPI_C = QLabel(self.frmAxisSliders_C)
        self.labelSPI_C.setObjectName(u"labelSPI_C")
        self.labelSPI_C.setGeometry(QRect(0, 190, 40, 25))
        self.labelSPI_C.setFrameShape(QFrame.Shape.Panel)
        self.labelSPI_C.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelSPI_C.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.labelABZ_C = QLabel(self.frmAxisSliders_C)
        self.labelABZ_C.setObjectName(u"labelABZ_C")
        self.labelABZ_C.setGeometry(QRect(50, 190, 40, 25))
        self.labelABZ_C.setFrameShape(QFrame.Shape.Panel)
        self.labelABZ_C.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelABZ_C.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.frmAxisSliders_C)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 160, 40, 25))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.frmAxisSliders_C)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 160, 40, 25))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sliderTarget_C.raise_()
        self.labelTargetReported_C.raise_()
        self.labelTarget_C.raise_()
        self.sliderSPI_C.raise_()
        self.sliderABZ_C.raise_()
        self.labelSPI_C.raise_()
        self.labelABZ_C.raise_()
        self.label_6.raise_()
        self.label_5.raise_()

        self.horizontalLayout_9.addWidget(self.frmAxisSliders_C)

        self.frmControls_C = QFrame(self.frmAxis_C)
        self.frmControls_C.setObjectName(u"frmControls_C")
        sizePolicy2.setHeightForWidth(self.frmControls_C.sizePolicy().hasHeightForWidth())
        self.frmControls_C.setSizePolicy(sizePolicy2)
        self.frmControls_C.setMaximumSize(QSize(250, 16777215))
        self.frmControls_C.setFrameShape(QFrame.Shape.NoFrame)
        self.frmControls_C.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frmControls_C)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.frmCenter_C = QFrame(self.frmControls_C)
        self.frmCenter_C.setObjectName(u"frmCenter_C")
        sizePolicy3.setHeightForWidth(self.frmCenter_C.sizePolicy().hasHeightForWidth())
        self.frmCenter_C.setSizePolicy(sizePolicy3)
        self.frmCenter_C.setFrameShape(QFrame.Shape.NoFrame)
        self.frmCenter_C.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.frmCenter_C)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.crmCenterButtons_C = QFrame(self.frmCenter_C)
        self.crmCenterButtons_C.setObjectName(u"crmCenterButtons_C")
        self.crmCenterButtons_C.setFrameShape(QFrame.Shape.NoFrame)
        self.crmCenterButtons_C.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.crmCenterButtons_C)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.btnNudgeUp_C = QPushButton(self.crmCenterButtons_C)
        self.btnNudgeUp_C.setObjectName(u"btnNudgeUp_C")

        self.verticalLayout_8.addWidget(self.btnNudgeUp_C)

        self.btnNudgeDown_C = QPushButton(self.crmCenterButtons_C)
        self.btnNudgeDown_C.setObjectName(u"btnNudgeDown_C")

        self.verticalLayout_8.addWidget(self.btnNudgeDown_C)


        self.horizontalLayout_6.addWidget(self.crmCenterButtons_C)

        self.lblNudgeCenter_C = QLabel(self.frmCenter_C)
        self.lblNudgeCenter_C.setObjectName(u"lblNudgeCenter_C")
        sizePolicy2.setHeightForWidth(self.lblNudgeCenter_C.sizePolicy().hasHeightForWidth())
        self.lblNudgeCenter_C.setSizePolicy(sizePolicy2)
        self.lblNudgeCenter_C.setFrameShape(QFrame.Shape.NoFrame)
        self.lblNudgeCenter_C.setFrameShadow(QFrame.Shadow.Plain)
        self.lblNudgeCenter_C.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lblNudgeCenter_C.setWordWrap(True)

        self.horizontalLayout_6.addWidget(self.lblNudgeCenter_C)


        self.verticalLayout_7.addWidget(self.frmCenter_C)

        self.labelEnabled_C = QLabel(self.frmControls_C)
        self.labelEnabled_C.setObjectName(u"labelEnabled_C")
        self.labelEnabled_C.setFrameShape(QFrame.Shape.NoFrame)
        self.labelEnabled_C.setFrameShadow(QFrame.Shadow.Plain)
        self.labelEnabled_C.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_7.addWidget(self.labelEnabled_C)

        self.frmPID_C = QFrame(self.frmControls_C)
        self.frmPID_C.setObjectName(u"frmPID_C")
        self.frmPID_C.setFrameShape(QFrame.Shape.NoFrame)
        self.frmPID_C.setFrameShadow(QFrame.Shadow.Raised)
        self.formLayout_3 = QFormLayout(self.frmPID_C)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.lblPIDAP_C = QLabel(self.frmPID_C)
        self.lblPIDAP_C.setObjectName(u"lblPIDAP_C")
        self.lblPIDAP_C.setMinimumSize(QSize(60, 16))
        self.lblPIDAP_C.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAP_C.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAP_C.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_3.setWidget(1, QFormLayout.ItemRole.FieldRole, self.lblPIDAP_C)

        self.lblPIDAI_C = QLabel(self.frmPID_C)
        self.lblPIDAI_C.setObjectName(u"lblPIDAI_C")
        self.lblPIDAI_C.setMinimumSize(QSize(60, 16))
        self.lblPIDAI_C.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAI_C.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAI_C.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_3.setWidget(3, QFormLayout.ItemRole.FieldRole, self.lblPIDAI_C)

        self.lblPIDAD_C = QLabel(self.frmPID_C)
        self.lblPIDAD_C.setObjectName(u"lblPIDAD_C")
        self.lblPIDAD_C.setMinimumSize(QSize(60, 16))
        self.lblPIDAD_C.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPIDAD_C.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPIDAD_C.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_3.setWidget(5, QFormLayout.ItemRole.FieldRole, self.lblPIDAD_C)

        self.frmKp_C = QFrame(self.frmPID_C)
        self.frmKp_C.setObjectName(u"frmKp_C")
        self.frmKp_C.setMinimumSize(QSize(60, 16))
        self.frmKp_C.setFrameShape(QFrame.Shape.Panel)
        self.frmKp_C.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKp_C = QPushButton(self.frmKp_C)
        self.btnKp_C.setObjectName(u"btnKp_C")
        self.btnKp_C.setGeometry(QRect(0, -1, 60, 20))
        self.btnKp_C.setMinimumSize(QSize(60, 16))
        self.btnKp_C.setText(u"0.000")
        self.btnKp_C.setFlat(True)

        self.formLayout_3.setWidget(1, QFormLayout.ItemRole.LabelRole, self.frmKp_C)

        self.frmKi_C = QFrame(self.frmPID_C)
        self.frmKi_C.setObjectName(u"frmKi_C")
        self.frmKi_C.setMinimumSize(QSize(60, 16))
        self.frmKi_C.setFrameShape(QFrame.Shape.Panel)
        self.frmKi_C.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKi_C = QPushButton(self.frmKi_C)
        self.btnKi_C.setObjectName(u"btnKi_C")
        self.btnKi_C.setGeometry(QRect(0, -1, 60, 20))
        self.btnKi_C.setMinimumSize(QSize(60, 16))
        self.btnKi_C.setText(u"0.000")
        self.btnKi_C.setFlat(True)

        self.formLayout_3.setWidget(3, QFormLayout.ItemRole.LabelRole, self.frmKi_C)

        self.frmKd_C = QFrame(self.frmPID_C)
        self.frmKd_C.setObjectName(u"frmKd_C")
        self.frmKd_C.setMinimumSize(QSize(60, 16))
        self.frmKd_C.setFrameShape(QFrame.Shape.Panel)
        self.frmKd_C.setFrameShadow(QFrame.Shadow.Raised)
        self.btnKd_C = QPushButton(self.frmKd_C)
        self.btnKd_C.setObjectName(u"btnKd_C")
        self.btnKd_C.setGeometry(QRect(0, -1, 60, 20))
        self.btnKd_C.setMinimumSize(QSize(60, 16))
        self.btnKd_C.setText(u"0.000")
        self.btnKd_C.setFlat(True)

        self.formLayout_3.setWidget(5, QFormLayout.ItemRole.LabelRole, self.frmKd_C)


        self.verticalLayout_7.addWidget(self.frmPID_C)


        self.horizontalLayout_9.addWidget(self.frmControls_C)


        self.verticalLayout_11.addWidget(self.frmAxis_C)


        self.horizontalLayout_10.addWidget(self.frmAxisEnable_C)


        self.verticalLayout_12.addWidget(self.frmAxisControls)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_12.addItem(self.verticalSpacer)

        qMain.setCentralWidget(self.qBody)
        self.menubar = QMenuBar(qMain)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1224, 30))
        qMain.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(qMain)
        self.statusbar.setObjectName(u"statusbar")
        qMain.setStatusBar(self.statusbar)

        self.retranslateUi(qMain)

        QMetaObject.connectSlotsByName(qMain)
    # setupUi

    def retranslateUi(self, qMain):
        qMain.setWindowTitle(QCoreApplication.translate("qMain", u"MainWindow", None))
        self.btnEEPROMWipe_A.setText(QCoreApplication.translate("qMain", u"Wipe Flash", None))
        self.btnEEPROMLoad_A.setText(QCoreApplication.translate("qMain", u"Restore from Flash", None))
        self.btnEEPROMSave_A.setText(QCoreApplication.translate("qMain", u"Save to Flash", None))
        self.btnSerialConnect.setText(QCoreApplication.translate("qMain", u"Connect", None))
        self.btnSerialDisconnect.setText(QCoreApplication.translate("qMain", u"Disconnect", None))
        self.btnSerialRefresh.setText(QCoreApplication.translate("qMain", u"Refresh", None))
        self.boxComportList.setCurrentText("")
        self.labelConnected.setText("")
        self.btnEnable_A.setText(QCoreApplication.translate("qMain", u"Enable Axis", None))
        self.labelTarget_A.setText(QCoreApplication.translate("qMain", u"target", None))
        self.labelTargetReported_A.setText(QCoreApplication.translate("qMain", u"report", None))
        self.labelABZ_A.setText(QCoreApplication.translate("qMain", u"encoder", None))
        self.labelSPI_A.setText(QCoreApplication.translate("qMain", u"absolute", None))
        self.label.setText(QCoreApplication.translate("qMain", u"SPI", None))
        self.label_2.setText(QCoreApplication.translate("qMain", u"ABZ", None))
        self.btnNudgeUp_A.setText(QCoreApplication.translate("qMain", u"^", None))
        self.btnNudgeDown_A.setText(QCoreApplication.translate("qMain", u"v", None))
        self.lblNudgeCenter_A.setText(QCoreApplication.translate("qMain", u"Nudge Center", None))
        self.labelEnabled_A.setText(QCoreApplication.translate("qMain", u"Axis: abled", None))
        self.lblPIDAP_A.setText(QCoreApplication.translate("qMain", u"Tune: P", None))
        self.lblPIDAI_A.setText(QCoreApplication.translate("qMain", u"Tune: I", None))
        self.lblPIDAD_A.setText(QCoreApplication.translate("qMain", u"Tune: D", None))
        self.btnEnable_B.setText(QCoreApplication.translate("qMain", u"Enable Axis", None))
        self.labelTarget_B.setText(QCoreApplication.translate("qMain", u"target", None))
        self.labelTargetReported_B.setText(QCoreApplication.translate("qMain", u"report", None))
        self.labelSPI_B.setText(QCoreApplication.translate("qMain", u"absolute", None))
        self.labelABZ_B.setText(QCoreApplication.translate("qMain", u"encoder", None))
        self.label_4.setText(QCoreApplication.translate("qMain", u"SPI", None))
        self.label_3.setText(QCoreApplication.translate("qMain", u"ABZ", None))
        self.btnNudgeUp_B.setText(QCoreApplication.translate("qMain", u"^", None))
        self.btnNudgeDown_B.setText(QCoreApplication.translate("qMain", u"v", None))
        self.lblNudgeCenter_B.setText(QCoreApplication.translate("qMain", u"Nudge Center", None))
        self.labelEnabled_B.setText(QCoreApplication.translate("qMain", u"Axis: abled", None))
        self.lblPIDAP_B.setText(QCoreApplication.translate("qMain", u"Tune: P", None))
        self.lblPIDAI_B.setText(QCoreApplication.translate("qMain", u"Tune: I", None))
        self.lblPIDAD_B.setText(QCoreApplication.translate("qMain", u"Tune: D", None))
        self.btnEnable_C.setText(QCoreApplication.translate("qMain", u"Enable Axis", None))
        self.labelTarget_C.setText(QCoreApplication.translate("qMain", u"target", None))
        self.labelTargetReported_C.setText(QCoreApplication.translate("qMain", u"report", None))
        self.labelSPI_C.setText(QCoreApplication.translate("qMain", u"absolute", None))
        self.labelABZ_C.setText(QCoreApplication.translate("qMain", u"encoder", None))
        self.label_6.setText(QCoreApplication.translate("qMain", u"SPI", None))
        self.label_5.setText(QCoreApplication.translate("qMain", u"ABZ", None))
        self.btnNudgeUp_C.setText(QCoreApplication.translate("qMain", u"^", None))
        self.btnNudgeDown_C.setText(QCoreApplication.translate("qMain", u"v", None))
        self.lblNudgeCenter_C.setText(QCoreApplication.translate("qMain", u"Nudge Center", None))
        self.labelEnabled_C.setText(QCoreApplication.translate("qMain", u"Axis: abled", None))
        self.lblPIDAP_C.setText(QCoreApplication.translate("qMain", u"Tune: P", None))
        self.lblPIDAI_C.setText(QCoreApplication.translate("qMain", u"Tune: I", None))
        self.lblPIDAD_C.setText(QCoreApplication.translate("qMain", u"Tune: D", None))
    # retranslateUi

